### ISSUE TITLE
Inconsistent format for 1.41 release assets

### ISSUE THREAD

**Issue by gvinaccia** [simonmichael/hledger#2299]
the 1.41 release assets are in zip format instead of the usual .tar.gz, and the linux zip archive includes a tarball

**Comment by Flimm** [comment]
The instructions for installing the Linux version on this page are incorrect: https://github.com/simonmichael/hledger/releases/tag/1.41 The instructions expect a `.tar.gz` file, whereas the download is a `.zip` file.

**Comment by simonmichael** [comment]
Thanks for the reports! 

> the 1.41 release assets are in zip format instead of the usual .tar.gz, and the linux zip archive includes a tarball

IIRC,

- everything is in a zip because of a github limitation; it essentially forces that
- linux and mac have a tarball inside the zip to preserve the executable file permissions (zip doesn't do that). It removes one source of error for installers.

> The instructions for installing the Linux version on this page are incorrect:

- they and the mac instructions should be correct now.

**Comment by gvinaccia** [comment]
Thank you @simonmichael for the quick reply and the wonderful piece of software

**Comment by simonmichael** [comment]
Thanks! I'll close this then, noting that an easier binary command would be nice.

**Comment by simonmichael** [comment]
I researched this again. Here are some links on the github zip limitation:

- https://github.com/actions/upload-artifact?tab=readme-ov-file#zip-archives
- https://github.com/actions/upload-artifact/issues/109

I have forgotten if the limitation is with the upload-artifact tool, or github releases in general. I kind of thought it was the latter.

So when I see tar.gz files on some projects' releases, eg https://github.com/jgm/pandoc/releases/tag/3.6, I'm assuming those were uploaded by hand. Or, they are actually zip files, containing a tar.gz file, I can't be bothered to check just now.

I also found some tools that aim to make downloading github binaries easier (eget, ubi, gah, gogo, and github's own gh tool).

And, I found a project that uses gh to create and upload artifacts to releases (instead of upload-artifact). Still not sure if that gets around the zip limitation but it was a useful discovery, I can use that in lots of ways.

**Comment by hseg** [comment]
@simonmichael Looking at https://cli.github.com/manual/gh_release_create (look for the example uploading `./dist/*.tgz`), it appears that may be a solution.

Returning to the old behaviour would be nice for me, since Arch Linux's `makepkg` tries to autoextract[1] the artifact, but ends up only unwrapping the `.zip` container, leaving the `.tar` intact. Which makes sense, because both are archive formats, so you wouldn't want the automagic to extract both.

[1]: https://gitlab.archlinux.org/pacman/pacman/-/blob/master/scripts/libmakepkg/source/file.sh.in#L85-153

**Comment by simonmichael** [comment]
Reopening this for future improvement.

**Comment by simonmichael** [comment]
I cleaned up the workflows a little. Currently we have

- four `binaries-*.yml` workflows that build tarballs (and a zip file on windows)
- `release.yml` that gathers those and gzips and zips the tarballs.
- `_release2.yml` is some kind of start at a better process.

@hseg if you have any time to help draft better workflows, that would be welcome.

**Comment by simonmichael** [comment]
action-gh-release may not explicitly zip, but I think it happens somehow as part of whatever github activity it invokes. 

You're right, here's what I found in _release2.yml:
```
# possible new way to create releases
# from https://github.com/Exodus-Privacy/exodus-core/blob/8e3023cbafbffd927ff3eaf67a0ed2eb0f92dfeb/.github/workflows/main.yml

release:
    name: Create Github release
    needs: build
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download archive
        uses: actions/download-artifact@v3
        with:
          name: release
          path: dist
      - name: Create release
        run: |
          cd dist
          echo "ARCHIVE=$(ls *.tar.gz)" >> $GITHUB_ENV
          gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --generate-notes
      - name: Upload archive to release
        run: gh release upload ${{ github.ref_name }} dist/$ARCHIVE
```
