### ISSUE TITLE
explore snap for gnu/linux packaging

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#595]
https://snapcraft.io
https://snapcraft.io/docs/build-snaps/your-first-snap
https://snapcraft.io/docs/reference/plugins/

**Comment by simonmichael** [comment]
I dropped this, help welcome. I was using this config in .../hledger/snap/snap.yaml:
```
#https://snapcraft.io/docs/build-snaps/your-first-snap                                                                                                                                                                                        
name: hledger # you probably want to 'snapcraft register <name>'                                                                                                                                                                              
version: '1.3+git' # just for humans, typically '1.2+git' or '1.3.2'                                                                                                                                                                          
summary: cross-platform tools for easily tracking money & time with plain text                                                                                                                                                                
description: |                                                                                                                                                                                                                                
  hledger is a cross-platform program for tracking money, time, or                                                                                                                                                                            
  any other commodity, using double-entry accounting and a simple,                                                                                                                                                                            
  editable file format                                                                                                                                                                                                                        
                                                                                                                                                                                                                                              
grade: stable # must be 'stable' to release into candidate/stable channels                                                                                                                                                                    
confinement: devmode # use 'strict' once you have the right plugs and slots                                                                                                                                                                   
                                                                                                                                                                                                                                              
apps:                                                                                                                                                                                                                                         
  hledger:                                                                                                                                                                                                                                    
    command: hledger                                                                                                                                                                                                                          
                                                                                                                                                                                                                                              
parts:                                                                                                                                                                                                                                        
  hledger:                                                                                                                                                                                                                                    
    plugin: make                                                                                                                                                                                                                              
```
