### ISSUE TITLE
hledger-web-1.5 build failure with yesod-1.6

### ISSUE THREAD

**Issue by DanBurton** [simonmichael/hledger#717]
As seen on the Stackage build server:

```
[ 7 of 17] Compiling Foundation       ( Foundation.hs, dist/build/Foundation.o )

Foundation.hs:155:5: error:
    ‘urlRenderOverride’ is not a (visible) method of class ‘Yesod’
    |
155 |     urlRenderOverride y (StaticR s) =
    |     ^^^^^^^^^^^^^^^^^

Foundation.hs:172:5: error:
    ‘shouldLog’ is not a (visible) method of class ‘Yesod’
    |
172 |     shouldLog _ _source level =
    |     ^^^^^^^^^
```

I was able to reproduce these errors locally like so:

```bash
stack unpack hledger-web-1.5 && cd hledger-web-1.5
edit stack.yaml # add the following stack.yaml
stack build
```

```yaml
# stack.yaml
resolver: nightly-2018-03-10
extra-deps:
- yesod-1.6.0
- conduit-1.3.0
- yesod-core-1.6.0
- yesod-form-1.6.0
- yesod-persistent-1.6.0
- persistent-2.8.1
- resourcet-1.2.0
- http-conduit-2.3.0
- conduit-extra-1.3.0
- yesod-static-1.6.0
```
